### ISSUE TITLE
Playing your game locally

### ISSUE THREAD

**Issue by Caue-Aron** [2dengine/lovebuilder#1]
I'm trying to launch my game on web browser (Firefox) localy, like this:
`file:///C:/Users/Usuario/Downloads/Isometric-web/index.html/?g=Isometric.love`
but it just wont work. This is my folder structure:
![image](https://github.com/2dengine/lovebuilder/assets/54822334/a329559c-5f05-4871-9cf7-737d7cb6934f)

**Comment by 2dengine** [comment]
Hello and thank you for the comment.
The lovebuilder is used to **fuse** your game for various platforms. While the lovebuilder can package your game for the web, the web version runs using love.js. Please note that the standalone love.js player can run games **without** building:
https://github.com/2dengine/love.js
love.js needs to be uploaded on an actual server (preferably Apache) so you cannot just run it locally inside a browser. Running the game locally inside a browser is not supported and it **does not** make sense. You might as well use the native binaries (love.exe) if you want to run the game locally.
Sorry about the misunderstanding and I will probably remove the "web" option from the builder to avoid further confusion.

**Comment by Caue-Aron** [comment]
I dont think the web version should be removed it was a lot of searching to find something like this! This site is totally awesome and i think that it should stay as is, i just didnt know youd need an actual server to run things.

**Comment by 2dengine** [comment]
We need the server to load assets and .love files asynchronously through Fetch and AJAX requests. Without a server the page will not load until all of the files have been downloaded. Certain browsers may block running JavaScript locally. It may be possible to get it working, but it is not very practical to run love.js without a server.
Thank you for your understanding,
Ivan
