### ISSUE TITLE
Malformed game executable

### ISSUE THREAD

**Issue by GwyrddGlas** [2dengine/lovebuilder#2]
Using the site to convert the zip to compiled executable is creating it malformed. 

Executable love2d error:
![math-runner_gLklvppA6m](https://github.com/2dengine/lovebuilder/assets/157061839/8458a923-a6c7-4420-bb4b-03aa42b4e226)

Loading it via vscode and the love2d extension works fine.
![love_XchLStLzXl](https://github.com/2dengine/lovebuilder/assets/157061839/cbae1399-228a-4c5a-a7da-fc53fa67f9d7)

**Comment by 2dengine** [comment]
The MacOS builds are also possibly malformed too, although I do not have the necessary hardware to test this issue properly.
